/*
* generated by Xtext
*/

package cz.jpikl.yafmt.clang.scl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class SimpleConstraintLanguageGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cContextualExpressionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cImplicationParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//// Uses unassigned rule call.
		////
		//// The return type is Expression (abstract class for all kinds of expressions).
		//// It is returned the result of ContextualExpression or Implication rule. 
		//Expression:
		//	ContextualExpression | Implication;
		public ParserRule getRule() { return rule; }

		//ContextualExpression | Implication
		public Alternatives getAlternatives() { return cAlternatives; }

		//ContextualExpression
		public RuleCall getContextualExpressionParserRuleCall_0() { return cContextualExpressionParserRuleCall_0; }

		//Implication
		public RuleCall getImplicationParserRuleCall_1() { return cImplicationParserRuleCall_1; }
	}

	public class ContextualExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ContextualExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cContextKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cContextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cContextIDTerminalRuleCall_1_0 = (RuleCall)cContextAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpressionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpressionImplicationParserRuleCall_3_0 = (RuleCall)cExpressionAssignment_3.eContents().get(0);
		
		//ContextualExpression:
		//	"context" context=ID ":" expression=Implication;
		public ParserRule getRule() { return rule; }

		//"context" context=ID ":" expression=Implication
		public Group getGroup() { return cGroup; }

		//"context"
		public Keyword getContextKeyword_0() { return cContextKeyword_0; }

		//context=ID
		public Assignment getContextAssignment_1() { return cContextAssignment_1; }

		//ID
		public RuleCall getContextIDTerminalRuleCall_1_0() { return cContextIDTerminalRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//expression=Implication
		public Assignment getExpressionAssignment_3() { return cExpressionAssignment_3; }

		//Implication
		public RuleCall getExpressionImplicationParserRuleCall_3_0() { return cExpressionImplicationParserRuleCall_3_0; }
	}

	public class ImplicationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Implication");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cDisjunctionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cImplicationLeftPartAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Alternatives cAlternatives_1_1 = (Alternatives)cGroup_1.eContents().get(1);
		private final Keyword cImpliesKeyword_1_1_0 = (Keyword)cAlternatives_1_1.eContents().get(0);
		private final Keyword cRequiresKeyword_1_1_1 = (Keyword)cAlternatives_1_1.eContents().get(1);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_1_1_2 = (Keyword)cAlternatives_1_1.eContents().get(2);
		private final Keyword cEqualsSignGreaterThanSignKeyword_1_1_3 = (Keyword)cAlternatives_1_1.eContents().get(3);
		private final Assignment cRightPartAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPartDisjunctionParserRuleCall_1_2_0 = (RuleCall)cRightPartAssignment_1_2.eContents().get(0);
		
		//Implication returns Expression:
		//	Disjunction ({Implication.leftPart=current} ("implies" | "requires" | "->" | "=>") rightPart=Disjunction)?;
		public ParserRule getRule() { return rule; }

		//Disjunction ({Implication.leftPart=current} ("implies" | "requires" | "->" | "=>") rightPart=Disjunction)?
		public Group getGroup() { return cGroup; }

		//Disjunction
		public RuleCall getDisjunctionParserRuleCall_0() { return cDisjunctionParserRuleCall_0; }

		//({Implication.leftPart=current} ("implies" | "requires" | "->" | "=>") rightPart=Disjunction)?
		public Group getGroup_1() { return cGroup_1; }

		//{Implication.leftPart=current}
		public Action getImplicationLeftPartAction_1_0() { return cImplicationLeftPartAction_1_0; }

		//"implies" | "requires" | "->" | "=>"
		public Alternatives getAlternatives_1_1() { return cAlternatives_1_1; }

		//"implies"
		public Keyword getImpliesKeyword_1_1_0() { return cImpliesKeyword_1_1_0; }

		//"requires"
		public Keyword getRequiresKeyword_1_1_1() { return cRequiresKeyword_1_1_1; }

		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_1_1_2() { return cHyphenMinusGreaterThanSignKeyword_1_1_2; }

		//"=>"
		public Keyword getEqualsSignGreaterThanSignKeyword_1_1_3() { return cEqualsSignGreaterThanSignKeyword_1_1_3; }

		//rightPart=Disjunction
		public Assignment getRightPartAssignment_1_2() { return cRightPartAssignment_1_2; }

		//Disjunction
		public RuleCall getRightPartDisjunctionParserRuleCall_1_2_0() { return cRightPartDisjunctionParserRuleCall_1_2_0; }
	}

	public class DisjunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Disjunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cExclusiveDisjunctionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cDisjunctionPartsAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Alternatives cAlternatives_1_1 = (Alternatives)cGroup_1.eContents().get(1);
		private final Keyword cOrKeyword_1_1_0 = (Keyword)cAlternatives_1_1.eContents().get(0);
		private final Keyword cVerticalLineKeyword_1_1_1 = (Keyword)cAlternatives_1_1.eContents().get(1);
		private final Assignment cPartsAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cPartsExclusiveDisjunctionParserRuleCall_1_2_0 = (RuleCall)cPartsAssignment_1_2.eContents().get(0);
		
		//// Uses assigned action: {ExplicitReturnType.memberVariable=value}.
		//// This particular case is also called tree rewrite action.
		////
		//// If there is no 'or' token, the rule simply returns result of the only one ExclusiveDisjunction rule.
		////
		//// Otherwise, instance of Disjunction is returned. Parts array contains results of parsed ExclusiveDisjunction 
		//// rules. The result of the first one ExclusiveDisjunction (current keyword) was in that case added 
		//// to the parts array. Current then became the resulting Disjunction.
		////    Disjunction disjunction = new Disjunction();
		////    disjunction.getParts().add(current);
		////    current = disjunction;
		//Disjunction returns Expression:
		//	ExclusiveDisjunction ({Disjunction.parts+=current} ("or" | "|") parts+=ExclusiveDisjunction)*;
		public ParserRule getRule() { return rule; }

		//ExclusiveDisjunction ({Disjunction.parts+=current} ("or" | "|") parts+=ExclusiveDisjunction)*
		public Group getGroup() { return cGroup; }

		//ExclusiveDisjunction
		public RuleCall getExclusiveDisjunctionParserRuleCall_0() { return cExclusiveDisjunctionParserRuleCall_0; }

		//({Disjunction.parts+=current} ("or" | "|") parts+=ExclusiveDisjunction)*
		public Group getGroup_1() { return cGroup_1; }

		//{Disjunction.parts+=current}
		public Action getDisjunctionPartsAction_1_0() { return cDisjunctionPartsAction_1_0; }

		//"or" | "|"
		public Alternatives getAlternatives_1_1() { return cAlternatives_1_1; }

		//"or"
		public Keyword getOrKeyword_1_1_0() { return cOrKeyword_1_1_0; }

		//"|"
		public Keyword getVerticalLineKeyword_1_1_1() { return cVerticalLineKeyword_1_1_1; }

		//parts+=ExclusiveDisjunction
		public Assignment getPartsAssignment_1_2() { return cPartsAssignment_1_2; }

		//ExclusiveDisjunction
		public RuleCall getPartsExclusiveDisjunctionParserRuleCall_1_2_0() { return cPartsExclusiveDisjunctionParserRuleCall_1_2_0; }
	}

	public class ExclusiveDisjunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExclusiveDisjunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cConjunctionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cExclusiveDisjunctionPartsAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Alternatives cAlternatives_1_1 = (Alternatives)cGroup_1.eContents().get(1);
		private final Keyword cXorKeyword_1_1_0 = (Keyword)cAlternatives_1_1.eContents().get(0);
		private final Keyword cCircumflexAccentKeyword_1_1_1 = (Keyword)cAlternatives_1_1.eContents().get(1);
		private final Assignment cPartsAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cPartsConjunctionParserRuleCall_1_2_0 = (RuleCall)cPartsAssignment_1_2.eContents().get(0);
		
		//ExclusiveDisjunction returns Expression:
		//	Conjunction ({ExclusiveDisjunction.parts+=current} ("xor" | "^") parts+=Conjunction)*;
		public ParserRule getRule() { return rule; }

		//Conjunction ({ExclusiveDisjunction.parts+=current} ("xor" | "^") parts+=Conjunction)*
		public Group getGroup() { return cGroup; }

		//Conjunction
		public RuleCall getConjunctionParserRuleCall_0() { return cConjunctionParserRuleCall_0; }

		//({ExclusiveDisjunction.parts+=current} ("xor" | "^") parts+=Conjunction)*
		public Group getGroup_1() { return cGroup_1; }

		//{ExclusiveDisjunction.parts+=current}
		public Action getExclusiveDisjunctionPartsAction_1_0() { return cExclusiveDisjunctionPartsAction_1_0; }

		//"xor" | "^"
		public Alternatives getAlternatives_1_1() { return cAlternatives_1_1; }

		//"xor"
		public Keyword getXorKeyword_1_1_0() { return cXorKeyword_1_1_0; }

		//"^"
		public Keyword getCircumflexAccentKeyword_1_1_1() { return cCircumflexAccentKeyword_1_1_1; }

		//parts+=Conjunction
		public Assignment getPartsAssignment_1_2() { return cPartsAssignment_1_2; }

		//Conjunction
		public RuleCall getPartsConjunctionParserRuleCall_1_2_0() { return cPartsConjunctionParserRuleCall_1_2_0; }
	}

	public class ConjunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Conjunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cNegationParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cConjunctionPartsAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Alternatives cAlternatives_1_1 = (Alternatives)cGroup_1.eContents().get(1);
		private final Keyword cAndKeyword_1_1_0 = (Keyword)cAlternatives_1_1.eContents().get(0);
		private final Keyword cAmpersandKeyword_1_1_1 = (Keyword)cAlternatives_1_1.eContents().get(1);
		private final Assignment cPartsAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cPartsNegationParserRuleCall_1_2_0 = (RuleCall)cPartsAssignment_1_2.eContents().get(0);
		
		//Conjunction returns Expression:
		//	Negation ({Conjunction.parts+=current} ("and" | "&") parts+=Negation)*;
		public ParserRule getRule() { return rule; }

		//Negation ({Conjunction.parts+=current} ("and" | "&") parts+=Negation)*
		public Group getGroup() { return cGroup; }

		//Negation
		public RuleCall getNegationParserRuleCall_0() { return cNegationParserRuleCall_0; }

		//({Conjunction.parts+=current} ("and" | "&") parts+=Negation)*
		public Group getGroup_1() { return cGroup_1; }

		//{Conjunction.parts+=current}
		public Action getConjunctionPartsAction_1_0() { return cConjunctionPartsAction_1_0; }

		//"and" | "&"
		public Alternatives getAlternatives_1_1() { return cAlternatives_1_1; }

		//"and"
		public Keyword getAndKeyword_1_1_0() { return cAndKeyword_1_1_0; }

		//"&"
		public Keyword getAmpersandKeyword_1_1_1() { return cAmpersandKeyword_1_1_1; }

		//parts+=Negation
		public Assignment getPartsAssignment_1_2() { return cPartsAssignment_1_2; }

		//Negation
		public RuleCall getPartsNegationParserRuleCall_1_2_0() { return cPartsNegationParserRuleCall_1_2_0; }
	}

	public class NegationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Negation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPrimaryExpressionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Keyword cNotKeyword_1_0_0 = (Keyword)cAlternatives_1_0.eContents().get(0);
		private final Keyword cExclamationMarkKeyword_1_0_1 = (Keyword)cAlternatives_1_0.eContents().get(1);
		private final Action cNegationAction_1_1 = (Action)cGroup_1.eContents().get(1);
		private final Assignment cExpressionAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cExpressionPrimaryExpressionParserRuleCall_1_2_0 = (RuleCall)cExpressionAssignment_1_2.eContents().get(0);
		
		//Negation returns Expression:
		//	PrimaryExpression | ("not" | "!") {Negation} expression=PrimaryExpression;
		public ParserRule getRule() { return rule; }

		//PrimaryExpression | ("not" | "!") {Negation} expression=PrimaryExpression
		public Alternatives getAlternatives() { return cAlternatives; }

		//PrimaryExpression
		public RuleCall getPrimaryExpressionParserRuleCall_0() { return cPrimaryExpressionParserRuleCall_0; }

		//("not" | "!") {Negation} expression=PrimaryExpression
		public Group getGroup_1() { return cGroup_1; }

		//"not" | "!"
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }

		//"not"
		public Keyword getNotKeyword_1_0_0() { return cNotKeyword_1_0_0; }

		//"!"
		public Keyword getExclamationMarkKeyword_1_0_1() { return cExclamationMarkKeyword_1_0_1; }

		//{Negation}
		public Action getNegationAction_1_1() { return cNegationAction_1_1; }

		//expression=PrimaryExpression
		public Assignment getExpressionAssignment_1_2() { return cExpressionAssignment_1_2; }

		//PrimaryExpression
		public RuleCall getExpressionPrimaryExpressionParserRuleCall_1_2_0() { return cExpressionPrimaryExpressionParserRuleCall_1_2_0; }
	}

	public class PrimaryExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PrimaryExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cFeatureIdAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cValueAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cValueIDTerminalRuleCall_0_1_0 = (RuleCall)cValueAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cImplicationParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//// Uses simple action: {ExplicitReturnType} memberVariable=value.
		////
		//// If there is an ID token, instance of FeatureId is returned. Value member contains the parsed ID.
		//// Otherwise (there is an expression inside brackets), the result of Implication rule is returned. 
		//PrimaryExpression returns Expression:
		//	{FeatureId} value=ID | "(" Implication ")";
		public ParserRule getRule() { return rule; }

		//{FeatureId} value=ID | "(" Implication ")"
		public Alternatives getAlternatives() { return cAlternatives; }

		//{FeatureId} value=ID
		public Group getGroup_0() { return cGroup_0; }

		//{FeatureId}
		public Action getFeatureIdAction_0_0() { return cFeatureIdAction_0_0; }

		//value=ID
		public Assignment getValueAssignment_0_1() { return cValueAssignment_0_1; }

		//ID
		public RuleCall getValueIDTerminalRuleCall_0_1_0() { return cValueIDTerminalRuleCall_0_1_0; }

		//"(" Implication ")"
		public Group getGroup_1() { return cGroup_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }

		//Implication
		public RuleCall getImplicationParserRuleCall_1_1() { return cImplicationParserRuleCall_1_1; }

		//")"
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	
	
	private ExpressionElements pExpression;
	private ContextualExpressionElements pContextualExpression;
	private ImplicationElements pImplication;
	private DisjunctionElements pDisjunction;
	private ExclusiveDisjunctionElements pExclusiveDisjunction;
	private ConjunctionElements pConjunction;
	private NegationElements pNegation;
	private PrimaryExpressionElements pPrimaryExpression;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public SimpleConstraintLanguageGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("cz.jpikl.yafmt.clang.scl.SimpleConstraintLanguage".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//// Uses unassigned rule call.
	////
	//// The return type is Expression (abstract class for all kinds of expressions).
	//// It is returned the result of ContextualExpression or Implication rule. 
	//Expression:
	//	ContextualExpression | Implication;
	public ExpressionElements getExpressionAccess() {
		return (pExpression != null) ? pExpression : (pExpression = new ExpressionElements());
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}

	//ContextualExpression:
	//	"context" context=ID ":" expression=Implication;
	public ContextualExpressionElements getContextualExpressionAccess() {
		return (pContextualExpression != null) ? pContextualExpression : (pContextualExpression = new ContextualExpressionElements());
	}
	
	public ParserRule getContextualExpressionRule() {
		return getContextualExpressionAccess().getRule();
	}

	//Implication returns Expression:
	//	Disjunction ({Implication.leftPart=current} ("implies" | "requires" | "->" | "=>") rightPart=Disjunction)?;
	public ImplicationElements getImplicationAccess() {
		return (pImplication != null) ? pImplication : (pImplication = new ImplicationElements());
	}
	
	public ParserRule getImplicationRule() {
		return getImplicationAccess().getRule();
	}

	//// Uses assigned action: {ExplicitReturnType.memberVariable=value}.
	//// This particular case is also called tree rewrite action.
	////
	//// If there is no 'or' token, the rule simply returns result of the only one ExclusiveDisjunction rule.
	////
	//// Otherwise, instance of Disjunction is returned. Parts array contains results of parsed ExclusiveDisjunction 
	//// rules. The result of the first one ExclusiveDisjunction (current keyword) was in that case added 
	//// to the parts array. Current then became the resulting Disjunction.
	////    Disjunction disjunction = new Disjunction();
	////    disjunction.getParts().add(current);
	////    current = disjunction;
	//Disjunction returns Expression:
	//	ExclusiveDisjunction ({Disjunction.parts+=current} ("or" | "|") parts+=ExclusiveDisjunction)*;
	public DisjunctionElements getDisjunctionAccess() {
		return (pDisjunction != null) ? pDisjunction : (pDisjunction = new DisjunctionElements());
	}
	
	public ParserRule getDisjunctionRule() {
		return getDisjunctionAccess().getRule();
	}

	//ExclusiveDisjunction returns Expression:
	//	Conjunction ({ExclusiveDisjunction.parts+=current} ("xor" | "^") parts+=Conjunction)*;
	public ExclusiveDisjunctionElements getExclusiveDisjunctionAccess() {
		return (pExclusiveDisjunction != null) ? pExclusiveDisjunction : (pExclusiveDisjunction = new ExclusiveDisjunctionElements());
	}
	
	public ParserRule getExclusiveDisjunctionRule() {
		return getExclusiveDisjunctionAccess().getRule();
	}

	//Conjunction returns Expression:
	//	Negation ({Conjunction.parts+=current} ("and" | "&") parts+=Negation)*;
	public ConjunctionElements getConjunctionAccess() {
		return (pConjunction != null) ? pConjunction : (pConjunction = new ConjunctionElements());
	}
	
	public ParserRule getConjunctionRule() {
		return getConjunctionAccess().getRule();
	}

	//Negation returns Expression:
	//	PrimaryExpression | ("not" | "!") {Negation} expression=PrimaryExpression;
	public NegationElements getNegationAccess() {
		return (pNegation != null) ? pNegation : (pNegation = new NegationElements());
	}
	
	public ParserRule getNegationRule() {
		return getNegationAccess().getRule();
	}

	//// Uses simple action: {ExplicitReturnType} memberVariable=value.
	////
	//// If there is an ID token, instance of FeatureId is returned. Value member contains the parsed ID.
	//// Otherwise (there is an expression inside brackets), the result of Implication rule is returned. 
	//PrimaryExpression returns Expression:
	//	{FeatureId} value=ID | "(" Implication ")";
	public PrimaryExpressionElements getPrimaryExpressionAccess() {
		return (pPrimaryExpression != null) ? pPrimaryExpression : (pPrimaryExpression = new PrimaryExpressionElements());
	}
	
	public ParserRule getPrimaryExpressionRule() {
		return getPrimaryExpressionAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
