/*
* generated by Xtext
*/
package cz.jpikl.yafmt.clang.scl.ui.contentassist;

import cz.jpikl.yafmt.clang.scl.ui.contentassist.AbstractSimpleConstraintLanguageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SimpleConstraintLanguageProposalProvider extends AbstractSimpleConstraintLanguageProposalProvider {

}
