/*
 * generated by Xtext
 */
package cz.jpikl.yafmt.clang.scl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimpleConstraintLanguageUiModule extends cz.jpikl.yafmt.clang.scl.ui.AbstractSimpleConstraintLanguageUiModule {
	public SimpleConstraintLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
