/*
 * generated by Xtext
 */
package cz.jpikl.yafmt.clang.scl;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class SimpleConstraintLanguageRuntimeModule extends cz.jpikl.yafmt.clang.scl.AbstractSimpleConstraintLanguageRuntimeModule {

}
