/*
 * generated by Xtext
 */
package cz.jpikl.yafmt.clang.scl;

import java.util.Properties;

import org.eclipse.xtext.Constants;
import org.eclipse.xtext.service.DefaultRuntimeModule;

import com.google.inject.Binder;
import com.google.inject.name.Names;

/**
 * Manual modifications go to {cz.jpikl.yafmt.clang.scl.SimpleConstraintLanguageRuntimeModule}
 */
 @SuppressWarnings("all")
public abstract class AbstractSimpleConstraintLanguageRuntimeModule extends DefaultRuntimeModule {

	protected Properties properties = null;

	@Override
	public void configure(Binder binder) {
		properties = tryBindProperties(binder, "cz/jpikl/yafmt/clang/scl/SimpleConstraintLanguage.properties");
		super.configure(binder);
	}
	
	public void configureLanguageName(Binder binder) {
		binder.bind(String.class).annotatedWith(Names.named(Constants.LANGUAGE_NAME)).toInstance("cz.jpikl.yafmt.clang.scl.SimpleConstraintLanguage");
	}
	
	public void configureFileExtensions(Binder binder) {
		if (properties == null || properties.getProperty(Constants.FILE_EXTENSIONS) == null)
			binder.bind(String.class).annotatedWith(Names.named(Constants.FILE_EXTENSIONS)).toInstance("scl");
	}
	
}
