
/*
 * generated by Xtext
 */
package cz.jpikl.yafmt.clang.scl.ui;

import org.eclipse.xtext.ui.DefaultUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Manual modifications go to {cz.jpikl.yafmt.clang.scl.ui.SimpleConstraintLanguageUiModule}
 */
@SuppressWarnings("all")
public abstract class AbstractSimpleConstraintLanguageUiModule extends DefaultUiModule {
	
	public AbstractSimpleConstraintLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	
	// contributed by org.eclipse.xtext.ui.generator.ImplicitUiFragment
	public com.google.inject.Provider<org.eclipse.xtext.resource.containers.IAllContainersState> provideIAllContainersState() {
		return org.eclipse.xtext.ui.shared.Access.getJavaProjectsState();
	}


}
